export const ROLE_PERMISSIONS = {
  SUPER_ADMIN: ['*'],
  EDITOR: ['VIEW_DASHBOARD', 'MANAGE_PAGES', 'MANAGE_BLOGS'],
  MARKETING_MANAGER: ['VIEW_DASHBOARD', 'MANAGE_LEADS', 'VIEW_ANALYTICS'],
  SEO_MANAGER: ['VIEW_DASHBOARD', 'MANAGE_SEO'],
  MEDIA_MANAGER: ['VIEW_DASHBOARD', 'MANAGE_MEDIA'],
};
